


###
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTcyNjg1OTA3NSwiZXhwIjoxNzI3NDYzODc1fQ.DrwxTTioWtBn4GkNz2oCAyyrWAb8JU7vGqYco8eNjpg

### Sign In
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "admin",
    "password": "admin"
}

### Sign Up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "admin",
    "lastName": "admin",
    "email": "adminadmin@email.com",
    "password": "admin"
}

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTcyNjg1OTA3NSwiZXhwIjoxNzI3NDYzODc1fQ.DrwxTTioWtBn4GkNz2oCAyyrWAb8JU7vGqYco8eNjpg

###
GET http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTcyNjg1OTA3NSwiZXhwIjoxNzI3NDYzODc1fQ.DrwxTTioWtBn4GkNz2oCAyyrWAb8JU7vGqYco8eNjpg

###
DELETE http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTcyNjg1OTA3NSwiZXhwIjoxNzI3NDYzODc1fQ.DrwxTTioWtBn4GkNz2oCAyyrWAb8JU7vGqYco8eNjpg