services:
  redis:
    build: ./redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./db/redis:/data
    restart: always
    networks:
      - default

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
